version: '2'
services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
        - LDAP_ORGANISATION=iesalixar
        - LDAP_DOMAIN=iesalixar.org
        - "LDAP_BASE_DN=dc=iesalixar,dc=org"
        - LDAP_ADMIN_PASSWORD=passiesalixar
    ports:
        - 389:389
        - 636:636